-- Operations system schema
-- Generated by the Operations Blueprint (damiankao.com/blueprint). Postgres.
-- A starting point: adjust types, add indexes and NOT NULL/CHECK constraints as you learn.

-- has many bom_lines; configured into product_variants
CREATE TABLE product_templates (
  id bigserial PRIMARY KEY,
  name text,
  params jsonb,  -- configurable option definitions
  base_price numeric(12,2)
);

-- a resolved configuration that can be costed and quoted
CREATE TABLE product_variants (
  id bigserial PRIMARY KEY,
  template_id bigint,
  option_values jsonb
);

-- referenced by bom_lines; belongs to a vendor
CREATE TABLE materials (
  id bigserial PRIMARY KEY,
  name text,
  type text,
  unit text,  -- unit of measure (sheet, board-foot, each)
  cost_per_unit numeric(12,4),
  vendor_id bigint
);

-- binds a product to the materials it consumes (the bill of materials)
CREATE TABLE bom_lines (
  id bigserial PRIMARY KEY,
  product_ref bigint,
  material_id bigint,
  qty numeric(12,3),
  unit text
);

-- a product's routing references these to compute labor
CREATE TABLE labor_ops (
  id bigserial PRIMARY KEY,
  name text,
  station text,
  std_minutes numeric(8,2),
  rate_per_hr numeric(10,2)
);

-- the raw stock you cut parts from
CREATE TABLE stock_items (
  id bigserial PRIMARY KEY,
  material_id bigint,
  sheet_w numeric(10,2),  -- for sheet stock
  sheet_h numeric(10,2),  -- for sheet stock
  length numeric(10,2),  -- for linear stock
  cost numeric(12,2)
);

-- parts nested onto stock_items to compute yield
CREATE TABLE cut_parts (
  id bigserial PRIMARY KEY,
  product_ref bigint,
  part_name text,
  w numeric(10,2),
  h numeric(10,2),
  qty integer
);

-- supplies materials; drives purchasing
CREATE TABLE vendors (
  id bigserial PRIMARY KEY,
  name text,
  lead_time_days integer,
  terms text
);

-- current stock levels, decremented on consumption
CREATE TABLE inventory (
  id bigserial PRIMARY KEY,
  item_ref bigint,  -- a material or stock_item (polymorphic; resolve in the API)
  on_hand numeric(12,3),
  location text
);

-- owns projects and quotes
CREATE TABLE clients (
  id bigserial PRIMARY KEY,
  name text,
  contact text,
  terms text
);

-- a job from quote through delivery
CREATE TABLE projects (
  id bigserial PRIMARY KEY,
  client_id bigint,
  status text,
  created_at timestamptz,
  due_date date
);

-- priced output of the engine; versioned
CREATE TABLE quotes (
  id bigserial PRIMARY KEY,
  project_id bigint,
  version integer,
  total numeric(12,2),
  status text
);

-- the line items, each priced by the engine
CREATE TABLE quote_lines (
  id bigserial PRIMARY KEY,
  quote_id bigint,
  product_ref bigint,
  qty numeric(12,2),
  unit_price numeric(12,2)
);

-- shipping / delivery scheduling
CREATE TABLE deliveries (
  id bigserial PRIMARY KEY,
  project_id bigint,
  scheduled_date date,
  address text,
  status text
);

-- what the floor actually consumed, compared back to the estimate
CREATE TABLE production_actuals (
  id bigserial PRIMARY KEY,
  project_id bigint,
  material_used numeric(12,3),
  time_used numeric(10,2)
);

-- Foreign keys
ALTER TABLE product_variants ADD CONSTRAINT fk_product_variants_template_id FOREIGN KEY (template_id) REFERENCES product_templates(id);
ALTER TABLE materials ADD CONSTRAINT fk_materials_vendor_id FOREIGN KEY (vendor_id) REFERENCES vendors(id);
ALTER TABLE bom_lines ADD CONSTRAINT fk_bom_lines_product_ref FOREIGN KEY (product_ref) REFERENCES product_templates(id);
ALTER TABLE bom_lines ADD CONSTRAINT fk_bom_lines_material_id FOREIGN KEY (material_id) REFERENCES materials(id);
ALTER TABLE stock_items ADD CONSTRAINT fk_stock_items_material_id FOREIGN KEY (material_id) REFERENCES materials(id);
ALTER TABLE cut_parts ADD CONSTRAINT fk_cut_parts_product_ref FOREIGN KEY (product_ref) REFERENCES product_templates(id);
ALTER TABLE projects ADD CONSTRAINT fk_projects_client_id FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE quotes ADD CONSTRAINT fk_quotes_project_id FOREIGN KEY (project_id) REFERENCES projects(id);
ALTER TABLE quote_lines ADD CONSTRAINT fk_quote_lines_quote_id FOREIGN KEY (quote_id) REFERENCES quotes(id);
ALTER TABLE quote_lines ADD CONSTRAINT fk_quote_lines_product_ref FOREIGN KEY (product_ref) REFERENCES product_variants(id);
ALTER TABLE deliveries ADD CONSTRAINT fk_deliveries_project_id FOREIGN KEY (project_id) REFERENCES projects(id);
ALTER TABLE production_actuals ADD CONSTRAINT fk_production_actuals_project_id FOREIGN KEY (project_id) REFERENCES projects(id);
