/**
 * project: the repo-level scaffolding files (README, docker-compose, env, gitignore, manifest).
 */
import { PRODUCTS, type Blueprint, type BlueprintInput } from '../blueprint-model';
import type { SchemaTable } from '../schema-model';
import type { ExportFile } from './skeleton';

const COMPOSE =
  'services:\n' +
  '  db:\n' +
  '    image: postgres:16\n' +
  '    environment:\n' +
  '      POSTGRES_PASSWORD: postgres\n' +
  '      POSTGRES_DB: ops\n' +
  '    ports:\n' +
  '      - "5432:5432"\n' +
  '    volumes:\n' +
  '      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro\n' +
  '      - pgdata:/var/lib/postgresql/data\n' +
  '  api:\n' +
  '    build:\n' +
  '      context: .\n' +
  '      dockerfile: api/Dockerfile\n' +
  '    environment:\n' +
  '      DATABASE_URL: postgresql://postgres:postgres@db:5432/ops\n' +
  '    ports:\n' +
  '      - "8000:8000"\n' +
  '    depends_on:\n' +
  '      - db\n' +
  '  # redis:   # enable when you add background jobs or caching\n' +
  '  #   image: redis:7\n' +
  '  # qdrant:  # enable when you add the knowledge layer (vector search over SOPs and specs)\n' +
  '  #   image: qdrant/qdrant\n' +
  'volumes:\n' +
  '  pgdata:\n';

const ENV_EXAMPLE = 'DATABASE_URL=postgresql://postgres:postgres@db:5432/ops\n';

const GITIGNORE = '__pycache__/\n*.pyc\n.env\n';

function readme(i: BlueprintInput): string {
  const label = PRODUCTS[i.product].label.toLowerCase();
  return (
    '# Operations system (starter)\n\n' +
    `Generated by the [Operations Blueprint](https://damiankao.com/blueprint) for a ${label} operation.\n` +
    'A foundation-first build: a relational core, an API that is the only writer, and everything priced\n' +
    'through one engine.\n\n' +
    '## Run\n\n' +
    '1. Copy `.env.example` to `.env`.\n' +
    '2. `docker compose up` (starts Postgres with `db/schema.sql` loaded, and the API on :8000).\n' +
    '3. Open `http://localhost:8000/health`.\n\n' +
    '## Build\n\n' +
    'Read `AGENTS.md`, then work through `TASKS.md` in order. Start with the cost engine\n' +
    '(`api/engine/cost.py`): it is the keystone everything else prices through.\n\n' +
    '## Layout\n\n' +
    '```\n' +
    'db/schema.sql      the relational source of truth (Postgres)\n' +
    'api/engine/cost.py the cost engine (build first)\n' +
    'api/routes/        HTTP surfaces, one per domain\n' +
    'AGENTS.md          rules and build order for the agent\n' +
    'TASKS.md           the build checklist\n' +
    'docs/blueprint.md  the full plan\n' +
    '```\n\n' +
    'The full plan, including the data model and the integrator notes, is in `docs/blueprint.md`.\n'
  );
}

export function projectFiles(i: BlueprintInput, tables: SchemaTable[], bp: Blueprint): ExportFile[] {
  const manifest = {
    generatedBy: 'Operations Blueprint (damiankao.com/blueprint)',
    input: i,
    tables: tables.map((t) => t.name),
    sections: bp.sections.map((s) => s.title),
  };
  return [
    { path: 'README.md', content: readme(i) },
    { path: 'docker-compose.yml', content: COMPOSE },
    { path: '.env.example', content: ENV_EXAMPLE },
    { path: '.gitignore', content: GITIGNORE },
    { path: 'blueprint.json', content: JSON.stringify(manifest, null, 2) + '\n' },
  ];
}
