/**
 * sql: render the typed schema as Postgres DDL (db/schema.sql).
 *
 * CREATE TABLE (columns + primary key) for every table, then foreign keys as ALTER TABLE
 * statements so the output is order-independent regardless of which tables the inputs include.
 */
import type { SchemaTable } from '../schema-model';

function createTable(t: SchemaTable): string {
  const cols = t.columns.map((c, idx) => {
    const last = idx === t.columns.length - 1;
    let line = `  ${c.name} ${c.type}${c.pk ? ' PRIMARY KEY' : ''}${last ? '' : ','}`;
    if (c.notes) line += `  -- ${c.notes}`;
    return line;
  });
  return `-- ${t.note}\nCREATE TABLE ${t.name} (\n${cols.join('\n')}\n);`;
}

export function schemaSql(tables: SchemaTable[]): string {
  const header =
    '-- Operations system schema\n' +
    '-- Generated by the Operations Blueprint (damiankao.com/blueprint). Postgres.\n' +
    '-- A starting point: adjust types, add indexes and NOT NULL/CHECK constraints as you learn.\n\n';

  const creates = tables.map(createTable).join('\n\n');

  const fks: string[] = [];
  for (const t of tables) {
    for (const c of t.columns) {
      if (c.references) {
        fks.push(
          `ALTER TABLE ${t.name} ADD CONSTRAINT fk_${t.name}_${c.name} ` +
            `FOREIGN KEY (${c.name}) REFERENCES ${c.references}(id);`
        );
      }
    }
  }

  return header + creates + '\n\n-- Foreign keys\n' + fks.join('\n') + '\n';
}
