-- Operations system schema
-- Generated by the Operations Blueprint (damiankao.com/blueprint). Postgres.
-- A starting point: adjust types, add indexes and NOT NULL/CHECK constraints as you learn.

-- has many bom_lines; appears in quote_lines
CREATE TABLE products (
  id bigserial PRIMARY KEY,
  name text,
  sku text,
  base_price numeric(12,2)
);

-- referenced by bom_lines; belongs to a vendor
CREATE TABLE materials (
  id bigserial PRIMARY KEY,
  name text,
  type text,
  unit text,  -- unit of measure (sheet, board-foot, each)
  cost_per_unit numeric(12,4),
  vendor_id bigint
);

-- binds a product to the materials it consumes (the bill of materials)
CREATE TABLE bom_lines (
  id bigserial PRIMARY KEY,
  product_ref bigint,
  material_id bigint,
  qty numeric(12,3),
  unit text
);

-- a product's routing references these to compute labor
CREATE TABLE labor_ops (
  id bigserial PRIMARY KEY,
  name text,
  station text,
  std_minutes numeric(8,2),
  rate_per_hr numeric(10,2)
);

-- supplies materials; drives purchasing
CREATE TABLE vendors (
  id bigserial PRIMARY KEY,
  name text,
  lead_time_days integer,
  terms text
);

-- owns projects and quotes
CREATE TABLE clients (
  id bigserial PRIMARY KEY,
  name text,
  contact text,
  terms text
);

-- a job from quote through delivery
CREATE TABLE projects (
  id bigserial PRIMARY KEY,
  client_id bigint,
  status text,
  created_at timestamptz,
  due_date date
);

-- priced output of the engine; versioned
CREATE TABLE quotes (
  id bigserial PRIMARY KEY,
  project_id bigint,
  version integer,
  total numeric(12,2),
  status text
);

-- the line items, each priced by the engine
CREATE TABLE quote_lines (
  id bigserial PRIMARY KEY,
  quote_id bigint,
  product_ref bigint,
  qty numeric(12,2),
  unit_price numeric(12,2)
);

-- what the floor actually consumed, compared back to the estimate
CREATE TABLE production_actuals (
  id bigserial PRIMARY KEY,
  project_id bigint,
  material_used numeric(12,3),
  time_used numeric(10,2)
);

-- Foreign keys
ALTER TABLE materials ADD CONSTRAINT fk_materials_vendor_id FOREIGN KEY (vendor_id) REFERENCES vendors(id);
ALTER TABLE bom_lines ADD CONSTRAINT fk_bom_lines_product_ref FOREIGN KEY (product_ref) REFERENCES products(id);
ALTER TABLE bom_lines ADD CONSTRAINT fk_bom_lines_material_id FOREIGN KEY (material_id) REFERENCES materials(id);
ALTER TABLE projects ADD CONSTRAINT fk_projects_client_id FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE quotes ADD CONSTRAINT fk_quotes_project_id FOREIGN KEY (project_id) REFERENCES projects(id);
ALTER TABLE quote_lines ADD CONSTRAINT fk_quote_lines_quote_id FOREIGN KEY (quote_id) REFERENCES quotes(id);
ALTER TABLE quote_lines ADD CONSTRAINT fk_quote_lines_product_ref FOREIGN KEY (product_ref) REFERENCES products(id);
ALTER TABLE production_actuals ADD CONSTRAINT fk_production_actuals_project_id FOREIGN KEY (project_id) REFERENCES projects(id);
